<?php return array(
    'root' => array(
        'pretty_version' => '1.6.9',
        'version' => '1.6.9.0',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'codeinwp/otter-blocks',
        'dev' => false,
    ),
    'versions' => array(
        'codeinwp/gutenberg-animation' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/gutenberg-animation',
            'aliases' => array(),
            'reference' => '77ce9ca0b1598e3645f10ce516ccfcefc33b0704',
            'dev_requirement' => false,
        ),
        'codeinwp/gutenberg-blocks' => array(
            'pretty_version' => '1.6.9',
            'version' => '1.6.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/gutenberg-blocks',
            'aliases' => array(),
            'reference' => 'c58fc700fe616d8b4f6029c109a869257d6daeed',
            'dev_requirement' => false,
        ),
        'codeinwp/gutenberg-css' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/gutenberg-css',
            'aliases' => array(),
            'reference' => 'ff3005e3cb149555378c6a319d7857086d2521fc',
            'dev_requirement' => false,
        ),
        'codeinwp/gutenberg-menu-icons' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/gutenberg-menu-icons',
            'aliases' => array(),
            'reference' => 'fce0fae088cc85001620d83253568aeec2af51c0',
            'dev_requirement' => false,
        ),
        'codeinwp/otter-blocks' => array(
            'pretty_version' => '1.6.9',
            'version' => '1.6.9.0',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'codeinwp/themeisle-sdk' => array(
            'pretty_version' => '3.2.21',
            'version' => '3.2.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeinwp/themeisle-sdk',
            'aliases' => array(),
            'reference' => 'cafd016b61ec0928c0234e312046782a77c14318',
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.5',
            'version' => '2.7.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'reference' => 'f640ac1bdddff06ea333a920c95bbad8872429ab',
            'dev_requirement' => false,
        ),
        'tubalmartin/cssmin' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tubalmartin/cssmin',
            'aliases' => array(),
            'reference' => '3cbf557f4079d83a06f9c3ff9b957c022d7805cf',
            'dev_requirement' => false,
        ),
    ),
);
